### ISSUE TITLE
Can I do searches without being logged in?

### ISSUE THREAD

**Issue by Fazendaaa** [lubien/popura#19]
Hi, I'm trying to do searches but do I really need to be logged to do so?

Code:
```javascript
const __popura = require( 'popura' );
const popura = __popura(  );

popura.searchAnimes( 'naruto')
      .then( anime =>  console.log( anime ) )
      .catch( issue => console.log( issue ) )
```

Terminal:
```javascript
{ HTTPError
    at stream.catch.then.data (/home/farm/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  message: 'Response code 401 (Unauthorized)',
  host: 'myanimelist.net',
  hostname: 'myanimelist.net',
  method: 'GET',
  path: '/api/anime/search.xml?q=naruto',
  statusCode: 401,
  statusMessage: 'Unauthorized' }
```

**Comment by lubien** [comment]
Unfortunally, yes. And it's MAL's API fault.

See more at: [API Documentation - Anime/Manga Search](https://myanimelist.net/modules.php?go=api#animemangasearch).
Or try for yourself on the browser: https://myanimelist.net/api/anime|manga/search.xml?q=full+metal

Xinil always says that they want to make a better API, but as far I've been seeing over the years, they aren't doing it.

![image](https://cloud.githubusercontent.com/assets/9121359/24833451/044069da-1c9f-11e7-83f2-6a8507af4efb.png)
