### ISSUE TITLE
Is it possible to pull user details using this?

### ISSUE THREAD

**Issue by NoobDoesMC** [lubien/popura#23]
E.g. given a username can i get that user's location?

**Comment by lubien** [comment]
This wrapper only supports data given by MAL's XML API. All supported data is on this repo's README.

![image](https://user-images.githubusercontent.com/9121359/35768477-3396e050-08db-11e8-96e9-faa4df67b359.png)

If you need more info you should webscrap it, unfortunately. 

I know there's another wrapper there (I think in PHP) that creates a REST API over scrapped data but I can't remember it's name.
